package cinemalib;
import java.awt.Toolkit;
import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 * Linguagem de Programação 1 - Projeto Final
 * @author Alielson, Fábio Melo, Gabriel, Yuri Felix
 * TelaPrincipal.java - Classe Aplicação e Janela Principal.
 */


public class TelaPrincipal extends javax.swing.JFrame {
    
    
    public static String nomedoarquivo = "meusfilmes";
   //metodos para serializar e deserializar
    public static void carregarDados(){
        
        Deserializador d = new Deserializador();

        try {
            
            listaFilmes = null;
            listaFilmes = (ArrayList<Filme>) d.deserializar(nomedoarquivo);
            
            
        } catch (Exception ex) {
            System.err.println("Falha ao carregar lista! - " +
            ex.toString());
        }
   
    }
    public static void escreverDados(){
        Serializador s = new Serializador();
        try{
            s.serializar(nomedoarquivo, listaFilmes);
        }catch (Exception ex){
            System.err.println("Falha - " +
            ex.toString());
        }
        
    }
    //metodo que vai atualizar a lista de filmes 
    public void atualizarLista() {
        carregarDados();
        
        DefaultListModel lst = new DefaultListModel();
        for(Filme f : listaFilmes){
                
                lst.addElement(f.getNome());
                
            }
        listagem.setModel(lst);
    }

    
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        
        
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoPesquisar = new javax.swing.JTextField();
        buttonOk = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dadosFilme = new javax.swing.JTextArea();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listagem = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuAdicionar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        sobrePrograma = new javax.swing.JMenuItem();

        setTitle("CineLibrary");
        setMinimumSize(new java.awt.Dimension(1005, 621));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        campoPesquisar.setText("Pesquisar...");
        campoPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPesquisarFocusGained(evt);
            }
        });
        campoPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPesquisarMouseClicked(evt);
            }
        });
        campoPesquisar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoPesquisarInputMethodTextChanged(evt);
            }
        });

        buttonOk.setText("OK");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNome.setText("Nome");

        dadosFilme.setEditable(false);
        dadosFilme.setBackground(javax.swing.UIManager.getDefaults().getColor("control"));
        dadosFilme.setColumns(20);
        dadosFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dadosFilme.setRows(5);
        dadosFilme.setText("Nenhum Filme Selecionado.");
        jScrollPane1.setViewportView(dadosFilme);

        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemalib/images/editar.png"))); // NOI18N
        buttonEditar.setText("EDITAR");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemalib/images/excluir.png"))); // NOI18N
        buttonExcluir.setText("EXCLUIR");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemalib/images/adicionar.png"))); // NOI18N
        buttonAdicionar.setText("ADICIONAR");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        listagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listagem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listagemMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listagemMouseReleased(evt);
            }
        });
        listagem.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listagemValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listagem);

        jButton1.setText("FECHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemalib/images/pesquisa-20.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDisabledIcon(null);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        menuArquivo.setText("Arquivo");

        menuAdicionar.setText("Adicionar Filme");
        menuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdicionarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuAdicionar);

        menuEditar.setText("Editar Filme");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuEditar);

        menuExcluir.setText("Excluir Filme");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        menuArquivo.add(menuExcluir);

        jMenuBar1.add(menuArquivo);

        jMenu3.setText("Ferramentas");

        jMenuItem3.setText("Listar Todos os Filmes");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        menuAjuda.setText("Ajuda");

        sobrePrograma.setText("Sobre o Programa");
        sobrePrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreProgramaActionPerformed(evt);
            }
        });
        menuAjuda.add(sobrePrograma);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonOk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPesquisar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonEditar)
                    .addComponent(buttonAdicionar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("CINEMALIB");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        
        String pesquisa = campoPesquisar.getText();
        if(campoPesquisar.getText() == null){
            return;
        }
        DefaultListModel lst = new DefaultListModel();
        for(int i=0;i<listaFilmes.size();i++){
            if(listaFilmes.get(i).getNome().indexOf(pesquisa)>=0){
                lst.addElement(listaFilmes.get(i).getNome());
            }
       
        }
        listagem.setModel(lst);
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        int editar = listagem.getLeadSelectionIndex();
       
        if(editar == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção");
        }else{
           TelaCadastro tc = new TelaCadastro();
            tc.setVisible(true);
            tc.recebeEditar(editar);
        }

    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        int apagar = listagem.getLeadSelectionIndex();
       
        if(apagar == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção");
        }else{
            JOptionPane.showConfirmDialog(rootPane,"Você deseja apagar? ");
            listaFilmes.remove(apagar);
            escreverDados();
            atualizarLista();
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);
        
        
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void listagemValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listagemValueChanged
        Filme sel = listaFilmes.get(listagem.getLeadSelectionIndex());
        
        
        dadosFilme.setText(sel.toStringTelaPrincipal());
        labelNome.setText(sel.getNome());
        
        
        
        
    }//GEN-LAST:event_listagemValueChanged

    private void listagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listagemMouseClicked
        listagem.clearSelection();
        atualizarLista();
    }//GEN-LAST:event_listagemMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void listagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listagemMouseReleased
        atualizarLista();
    }//GEN-LAST:event_listagemMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void campoPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarMouseClicked
        campoPesquisar.setText("");
    }//GEN-LAST:event_campoPesquisarMouseClicked

    private void campoPesquisarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoPesquisarInputMethodTextChanged
        
    }//GEN-LAST:event_campoPesquisarInputMethodTextChanged

    private void campoPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarFocusGained
        
    }//GEN-LAST:event_campoPesquisarFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sobreProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreProgramaActionPerformed
        TelaSobrePrograma ts = new TelaSobrePrograma();
        ts.setVisible(true);       
    }//GEN-LAST:event_sobreProgramaActionPerformed

    private void menuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarActionPerformed
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);
      
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdicionarActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        int editar = listagem.getLeadSelectionIndex();
       
        if(editar == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção");
        }else{
           TelaCadastro tc = new TelaCadastro();
            tc.setVisible(true);
            tc.recebeEditar(editar);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        int apagar = listagem.getLeadSelectionIndex();
       
        if(apagar == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma opção");
        }else{
            JOptionPane.showConfirmDialog(rootPane,"Você deseja apagar? ");
            listaFilmes.remove(apagar);
            escreverDados();
            atualizarLista();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_menuExcluirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                TelaPrincipal tp = new TelaPrincipal();
                tp.setVisible(true);
                tp.atualizarLista();
                
            }
            
        });
        
       
        
        
    }
    
    public static List<Filme> listaFilmes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonOk;
    private javax.swing.JTextField campoPesquisar;
    private javax.swing.JTextArea dadosFilme;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelNome;
    private javax.swing.JList<String> listagem;
    private javax.swing.JMenuItem menuAdicionar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem sobrePrograma;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/logo16.png")));
        
    }


    
    
    
}
